export const Action = {
  GET_LIVE_MATCHES: 'GET_LIVE_MATCHES',
  GET_THIS_MONTH_MATCHES: 'GET_THIS_MONTH_MATCHES',
  GET_LAST_MONTH_MATCHES: 'GET_LAST_MONTH_MATCHES',
  GET_SELECTED_MONTH_MATCHES: 'GET_SELECTED_MONTH_MATCHES',
  GET_UPCOMING_MATCHES: 'GET_UPCOMING_MATCHES',
  SET_SELECTED_MONTH: 'SET_SELECTED_MONTH'
}

export const Mutation = {
  SET_LIVE_MATCHES: 'SET_LIVE_MATCHES',
  SET_THIS_MONTH_MATCHES: 'SET_THIS_MONTH_MATCHES',
  SET_LAST_MONTH_MATCHES: 'SET_LAST_MONTH_MATCHES',
  SET_SELECTED_MONTH_MATCHES: 'SET_SELECTED_MONTH_MATCHES',
  SET_UPCOMING_MATCHES: 'SET_UPCOMING_MATCHES',
  SET_SELECTED_MONTH: 'SET_SELECTED_MONTH',
  SET_ERROR: 'SET_ERROR'
}
